
@baseUrl = http://localhost:3000/api

# @name getAllPosts
GET {{baseUrl}}/posts

###

# @name addPost
POST {{baseUrl}}/posts
Content-Type: application/json

{
    "title": "Title abcd",
    "categoryId": 1,
    "status": "dang cam thay rat vui",
    "image": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252FPh20769_Lap4-7380213f-b3ca-4a67-8c77-7ed077dfe5a3/ImagePicker/93ac9f34-c3ac-4ebe-9866-7c96a985836d.jpeg",
    "author": "Le gia tuan",
    "content": "day la mot chiec may tinh gaming"
}

###

# @name updatePost
PATCH {{baseUrl}}/posts/3
Content-Type: application/json

{
    "categoryId": 2,
    "title": "Tao là ai"
}

###

# @name removePost
DELETE {{baseUrl}}/posts/4
Content-Type: application/json